---
version: "3.8"
services:
  radarr:
    image: ghcr.io/Sideral-Tech/purpur-docker:latest
    container_name: purpur
    volumes:
      - /data/purpur:/app
    ports:
      - 25565:25565
    restart: unless-stopped

